### ISSUE TITLE
More Specific install instructions plz

### ISSUE THREAD

**Issue by schneekluth** [thomasloven/lovelace-flower-card#3]
Hey,
I've tried to use your custom-card but getting this error:

![flower-card](https://user-images.githubusercontent.com/5740913/56738604-3f250e00-676d-11e9-934a-0e00d0190b91.png)

I've created the following folder structure in .homeassistant/www/:

~~~
lovelace-flower-card/
├── data
│   └── data.js
├── flower-card.js
└── Images
    ├── abelia chinensis.jpg
    ├── abelia dielsii.jpg
    ├── abelia x grandiflora.jpg
    ├── abelia x.jpg
     ...
~~~

in `lovelace-ui.yaml` i have:
~~~
  - type: module
    url: /customcards/lovelace-flower-card/flower-card.js
~~~

**Comment by iantrich** [comment]
Check your browser console, it is likely telling you to go to https://github.com/thomasloven/lovelace-card-tools to install card-tools

**Comment by thomasloven** [comment]
As Ian says, the instructions are *right there in the error message*. Also it's not supposed to be easy yet. As stated at the top of the readme this is considered Early Beta.

**Comment by schneekluth** [comment]
Sorry, I forgot about this part... I have installed card tools but it is still not displayed in latest Firefox. I've just opened Chromium and Card is shown as expected. My fault. It's a compatibility issue with Firefox.
