### ISSUE TITLE
Convert problem

### ISSUE THREAD

**Issue by mredone** [thomasloven/lovelace-flower-card#4]
I have problem with convert database

i have that error:
`python3 convert.py plant.csv > data.js
Traceback (most recent call last):
  File "convert.py", line 14, in <module>
    data[line[0]] = list(line[i] for i in [1,2,19,18,21,20,25,24,27,26])
  File "convert.py", line 14, in <genexpr>
    data[line[0]] = list(line[i] for i in [1,2,19,18,21,20,25,24,27,26])
IndexError: list index out of range`

Database id from [this](https://docs.google.com/spreadsheets/d/1leBAjGMOo6NHTDgq1x16LsFfaQlH70F1YLy7tAcZIIc/edit#gid=0) place

**Comment by fernandex00** [comment]
@mredone hi how do you solve this issue?
