### ISSUE TITLE
more info error

### ISSUE THREAD

**Issue by madmicio** [thomasloven/lovelace-flower-card#5]
![flora card more info](https://user-images.githubusercontent.com/42836292/58574585-9755a100-8240-11e9-9697-43ebcf6ea31a.JPG)

why do I have this visualization?

**Comment by sn3ak** [comment]
There's not enough information here to answer your question. Not being a programmer, I would say by the looks of it, that your plant configuration is incorrect.

Are you manually configuring your sensor? is it auto-detected by ESPHome, or MQTT?  what does your plant definition look like?

my sensors are auto detected by ESPHome, where I defined a miflora sensor as sensor.three. here's a working plant definition:

```
Plant 3:
  sensors:
    moisture: sensor.three_moisture
#    battery: sensor.three_battery_level
    temperature: sensor.three_temperature
    conductivity: sensor.three_soil_conductivity
    brightness: sensor.three_illuminance
```
